version: '3'
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf.d:/etc/nginx/conf.d"
    links:
      - app:app
    restart: always
  db:
    build: ./mysql/
    image: mysql:5.7
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    expose:
      - 3314
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d/
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    restart: always
  app:
    build: ./app/
    expose:
      - "80"
    links:
      - db:db
    restart: always
